application: stationboard
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /
  static_files: index.html
  upload: index.html
- url: /(.*\.html)
  static_files: \1
  upload: .*\.html
